<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_boats_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>d2373786-1f34-49a5-b633-c2d4d285d8ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq26u0NLXLX3goXcHmxKy4B0MbQb0vXXaZKqrOOhBJjW4A8IPLDv6FwfEBfYlMUSy8iOn2qhsqtavkBaMawqVj9vQT2dlBDrW1IFNpE9yaYrBpGxuReEMzduv8fsWlvO2gJ2fKRBjmAzR0xDUY6KuzHwPbfyn97fn7IxQo9y5ZfOmvG4KTELO-uwm0JjcKSONUQQVQf2B&amp;k=6Le-egkAAAAAAJDJwqdyhFw6F3clHUnH6KBZfQgb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dispostable - View message/iframe_html1body1div3div4iframe1_c-7mro1m2n5ksd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq26u0NLXLX3goXcHmxKy4B0MbQb0vXXaZKqrOOhBJjW4A8IPLDv6FwfEBfYlMUSy8iOn2qhsqtavkBaMawqVj9vQT2dlBDrW1IFNpE9yaYrBpGxuReEMzduv8fsWlvO2gJ2fKRBjmAzR0xDUY6KuzHwPbfyn97fn7IxQo9y5ZfOmvG4KTELO-uwm0JjcKSONUQQVQf2B&amp;k=6Le-egkAAAAAAJDJwqdyhFw6F3clHUnH6KBZfQgb')])[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AGdBq26u0NLXLX3goXcHmxKy4B0MbQb0vXXaZKqrOOhBJjW4A8IPLDv6FwfEBfYlMUSy8iOn2qhsqtavkBaMawqVj9vQT2dlBDrW1IFNpE9yaYrBpGxuReEMzduv8fsWlvO2gJ2fKRBjmAzR0xDUY6KuzHwPbfyn97fn7IxQo9y5ZfOmvG4KTELO-uwm0JjcKSONUQQVQf2B&amp;k=6Le-egkAAAAAAJDJwqdyhFw6F3clHUnH6KBZfQgb']</value>
   </webElementXpaths>
</WebElementEntity>
