<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>5edc2ee7-620e-4b03-a9f6-25b89bed87b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq270DD6VG7szcZ7zOhnAb4sBE3wIBvCbFuWSlNa0G2YZmdZ4rg_wQjNrwrK4SZJcimhnSMQfGuONhoGA0xGHOR0HsLBkEwsLp4f3AzsbJp6CCxp5KQQr0DdcaqRW3Gii45wWWr-gaF5UjqOxTxsJoJ096N9yik-3s5jr8tjzjpN7YXQL68ltv1cN4-llxDKF42A8L-wn&amp;k=6Le-egkAAAAAAJDJwqdyhFw6F3clHUnH6KBZfQgb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dispostable - View message/iframe_html1body1div3div4iframe1_c-36pnc0vetvdm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq270DD6VG7szcZ7zOhnAb4sBE3wIBvCbFuWSlNa0G2YZmdZ4rg_wQjNrwrK4SZJcimhnSMQfGuONhoGA0xGHOR0HsLBkEwsLp4f3AzsbJp6CCxp5KQQr0DdcaqRW3Gii45wWWr-gaF5UjqOxTxsJoJ096N9yik-3s5jr8tjzjpN7YXQL68ltv1cN4-llxDKF42A8L-wn&amp;k=6Le-egkAAAAAAJDJwqdyhFw6F3clHUnH6KBZfQgb')])[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AGdBq270DD6VG7szcZ7zOhnAb4sBE3wIBvCbFuWSlNa0G2YZmdZ4rg_wQjNrwrK4SZJcimhnSMQfGuONhoGA0xGHOR0HsLBkEwsLp4f3AzsbJp6CCxp5KQQr0DdcaqRW3Gii45wWWr-gaF5UjqOxTxsJoJ096N9yik-3s5jr8tjzjpN7YXQL68ltv1cN4-llxDKF42A8L-wn&amp;k=6Le-egkAAAAAAJDJwqdyhFw6F3clHUnH6KBZfQgb']</value>
   </webElementXpaths>
</WebElementEntity>
